Create-app
js-tasks-ru/vue-20240924_daniil064 pull request #2
Opened 2024-10-10 13:01 UTC by Daniil-Evtuhov

Реализовано Vue приложение, которое рендерит в элемент #app строку "Сегодня DATE", где DATE — текущая дата локализованая в формате { dateStyle: long }.

2024-10-10 13:01 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-10-11 11:22 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-13 22:59 UTC, ShGKme requested changes

2024-10-13 22:59 UTC, ShGKme commented on 01-basics/20-weather/WeatherApp.js
> +        <li v-for="weather in getWeatherData()" class="weather-card" :class="{'weather-card--night': hasNight(weather)}">
Напомню, что, хотя это не запрещено, лучше избегать вызова методов в шаблоне. Это делает его менее декларативным, и заставляет беспокоиться о его производительности или наличию у него побочных эффектов.

Это допустимо для простых утилит, например, `hasNight`. Но `getWeatherData` получает новые данные. В итоге каждый рендеринг компонента будет с новым массивом новых объектов, приводя к лишним ре-рендерам.

2024-10-14 07:06 UTC, Daniil-Evtuhov commented on 01-basics/20-weather/WeatherApp.js
> +        <li v-for="weather in getWeatherData()" class="weather-card" :class="{'weather-card--night': hasNight(weather)}">
Что в таком случае лучше использовать? Computed? Или присваивать значения глобальной переменной?

2024-10-14 23:03 UTC, ShGKme commented on 01-basics/20-weather/WeatherApp.js
> +        <li v-for="weather in getWeatherData()" class="weather-card" :class="{'weather-card--night': hasNight(weather)}">
`computed` нужен, когда требуется результат вычисления от других реактивных данных, чтобы при изменении зависимостей получить и актуальный вычисляемый результат.

Здесь данные статичны и получаются единожды, поэтому их достаточно один раз сохранить в переменную/свойство компонента в `setup` и затем использовать эти данные в шаблоне.

2024-10-16 05:32 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-20 20:35 UTC, ShGKme approved these changes

2024-10-20 20:35 UTC, merged